{% set name = "prody" %}
{% set version = "2.6.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/prody/{{ name }}.git
  git_tag: v2.6.1


build:
  number: 1
  entry_points:
    - prody = prody.apps:prody_main
    - evol = prody.apps:evol_main
    

requirements:
  build:

    - python 
    - biopython
    - requests
    - setuptools
    - scipy
    - pyparsing <=3.1.1
    - conda-build
    - pip
    - numpy >=1.10
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - {{ stdlib("c") }}  # [build_platform != target_platform]
    - libgfortran5
  

  host:
    - python 
    - pip >=22
    - setuptools
    - numpy >=1.10
    - scipy
    - pyparsing <=3.1.1
    - biopython
    - requests
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - {{ stdlib("c") }}  # [build_platform != target_platform]
    - libgfortran5
  run:
    - python 
    - numpy >=1.10
    - scipy
    - pyparsing <=3.1.1
    - biopython
    - pip
    - setuptools
    - requests

test:
  requires:
    - python 
    - numpy >=1.10
    - scipy
    - pyparsing <=3.1.1
    - biopython
    - pip
    - setuptools
    - requests
    - pytest
    - pytest-xprocess
  commands:
    - prody --help
    - evol --help
  imports:
    - prody
    - prody.atomic
    - prody.database
    - prody.dynamics
    - prody.ensemble
    - prody.kdtree.kdtree
    - prody.kdtree
    - prody.measure
    - prody.proteins
    - prody.sequence
    - prody.trajectory


about:
  home: http://www.bahargroup.org/prody/
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: ProDy is a free and open-source Python package for protein structure, dynamics, and sequence analysis, developed by the Bahar lab.
  description: |
    ProDy is a free and open-source Python package for protein 
    structure, dynamics, and sequence analysis, developed by the
    Bahar lab. It allows for comparative analysis and modeling of 
    protein structural  dynamics and sequence co-evolution. Fast 
    and flexible ProDy API is for interactive usage as well as 
    application development. ProDy also comes with several analysis 
    applications and a graphical user interface for visual analysis.
  doc_url: http://www.bahargroup.org/prody/manual/
  dev_url: https://github.com/prody/ProDy

extra:
  recipe-maintainers:
    - AnthonyBogetti
    - jamesmkrieger
    - simonbray
    - vbadwaj
