{% set name = "ProDy" %}
{% set version = "2.5rc1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jamesmkrieger/ProDy/archive/v{{ version }}.tar.gz
  sha256: ab25f54230f2731d05aa966879361ce803b43877895e49609924c9b24f38284c

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install -Ue . -vv && {{ PYTHON }} setup.py build_ext --inplace --force
  entry_points:
    - prody = prody.apps:prody_main
    - evol = prody.apps:evol_main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python >3.7,<3.12
    - pip <21.1
    - setuptools
    - numpy >=1.10,<1.25
  run:
    - python >3.7,<3.12
    - biopython
    - matplotlib-base
    - pyparsing <=3.1.1
    - requests
    - setuptools  # requires pkg_resources at runtime
    - scipy
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - python >3.7,<3.12
    - biopython
    - pyparsing <=3.1.1
    - requests
    - setuptools  # requires pkg_resources at runtime
    - scipy
    - {{ pin_compatible('numpy') }}    
  commands:
    - prody --help
    - evol --help
  imports:
    - prody
    - prody.atomic
    - prody.database
    - prody.dynamics
    - prody.ensemble
    - prody.kdtree
    - prody.measure
    - prody.proteins
    - prody.sequence
    - prody.trajectory

about:
  home: http://www.bahargroup.org/prody/
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: ProDy is a free and open-source Python package for protein structure, dynamics, and sequence analysis, developed by the Bahar lab.
  description: |
    ProDy is a free and open-source Python package for protein 
    structure, dynamics, and sequence analysis, developed by the
    Bahar lab. It allows for comparative analysis and modeling of 
    protein structural  dynamics and sequence co-evolution. Fast 
    and flexible ProDy API is for interactive usage as well as 
    application development. ProDy also comes with several analysis 
    applications and a graphical user interface for visual analysis.
  doc_url: http://www.bahargroup.org/prody/manual/
  dev_url: https://github.com/prody/ProDy

extra:
  recipe-maintainers:
    - jamesmkrieger
    - simonbray
